version: '3.8'
services:
  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "3001:3001"
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - menu-service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3003:3003"
  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    ports:
      - "3004:3004"
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - reservation-service
