apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
  namespace: restaurant-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - name: menu
        image: menu-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: restaurant-demo
spec:
  selector:
    app: menu
  ports:
    - port: 3001
      targetPort: 3001
