apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  namespace: restaurant-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - name: reservation
        image: reservation-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: restaurant-demo
spec:
  selector:
    app: reservation
  ports:
    - port: 3004
      targetPort: 3004
