name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push menu-service
        uses: docker/build-push-action@v5
        with:
          context: ./menu-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/menu-service:latest

      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/order-service:latest

      - name: Build and push payment-service
        uses: docker/build-push-action@v5
        with:
          context: ./payment-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/payment-service:latest

      - name: Build and push reservation-service
        uses: docker/build-push-action@v5
        with:
          context: ./reservation-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/reservation-service:latest

      - name: Build and push gateway-service
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/api-gateway:latest
