name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push menu-service image
        uses: docker/build-push-action@v4
        with:
          context: ./menu-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/menu-service:latest

      - name: Build and push order-service image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/order-service:latest

      - name: Build and push payment-service image
        uses: docker/build-push-action@v4
        with:
          context: ./payment-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/payment-service:latest

      - name: Build and push reservation-service image
        uses: docker/build-push-action@v4
        with:
          context: ./reservation-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/reservation-service:latest

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/api-gateway:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl config view
      - name: Apply k8s manifests
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/menu-deployment.yaml
          kubectl apply -f k8s/order-deployment.yaml
          kubectl apply -f k8s/payment-deployment.yaml
          kubectl apply -f k8s/reservation-deployment.yaml
          kubectl apply -f k8s/gateway-deployment.yaml
          kubectl apply -f k8s/ingress.yaml
